### ISSUE TITLE
Warmstart

### ISSUE THREAD

**Issue by julianwanner** [darnstrom/daqp#1]
Dear Darnstrom,

thank you for sharing this wonderful lightweight QP solver. After a few tests, this solver seems to be the perfekt fit for my problem. I am using it for a small QP with 6 variables and 80 unequality constraints und so far it even outperforms my goto solver qpOASES. 

The solver runs on an embbeded hardware and solves an inverse kinematic problem with graduallly changing objective function and constraints. In between steps the the parameter changes are therefore small. Could you comment on how to poperly warstart the solver from the previous solution? 

So far I am using update_ldp()  followed by daqp_solve() because that is what in you do in the Matlab .update() and .solve() method. But I am not sure if update_ldp() is really neccessary. 

By the way your Matlab [documentation](https://darnstrom.github.io/daqp/start/matlab) has a typo. The command d.solve(H,f,A,bupper,blower,sense) does not work.

Best wishes

Julian

**Comment by darnstrom** [comment]
First of all, thank you for catching the typo in the documentation! 

As for the warm start, the current way of doing it is, as you mention, by using update_ldp() followed daqp_solve(). How much work from previous solves can be saved depend on which problem data is updated. If the Hessian H and/or the normals of the constraints A change, the internal LDL factorization will have to be redone from scratch. Such a refacatorization is, however, not necessary if only the linear term in the objective function f and/or the constraint term in the constraints b changes.  

If your problem falls in to the former case of changing H and/or A you either have to call 
activate_constraints() after update_ldp() if you want to warm start from the previous active set, or call deactivate_constraints() if you want to cold start (this is not necessary if only f and/or b change, i.e., update_ldp() followed by daqp_solve() is sufficient in that case). 

I have used the solver mostly in cases where only f and/or b need to be updated. Hence, the warm-starting procedure when H and/or A change is a bit more crude, but is, nevertheless, possible by running update_ldp() followed by activate_constraints() and daqp_solve() as mentioned above.

**Comment by julianwanner** [comment]
Thanks for clearing that up. My problem unfortunaltely falls into the first category, i.e. H and A change. So the LDL factorization will have to be redone. Nevertheless, this solver outperforms the other solvers I tried.
