### ISSUE TITLE
integer variable

### ISSUE THREAD

**Issue by pengfzhou** [darnstrom/daqp#29]
how to set x to be integer

**Comment by darnstrom** [comment]
Thank you for your question. 

Currently DAQP does not support integer variables, only binary variables (more generally binary constraints).
This can be enforced by setting marking a constraint to be binary, which will force it to either be fixed at its upper or lower bound. 
Concretely, a constraint is marked as binary by setting the corresponding element in sense to 16 (i.e., setting the 5th bit to 1); for more information, see [this](https://darnstrom.github.io/daqp/parameters/#constraint-classification.) page.


As an example, in the tutorial problem considered [here]( https://darnstrom.github.io/daqp/start/interface) one can force the second variable to be -2 or 2 by settings the second element of sense to 16.
