### ISSUE TITLE
Cvxpy interface help/suggestions

### ISSUE THREAD

**Issue by enzbus** [darnstrom/daqp#31]
Hello @darnstrom and thanks for publishing DAQP! I started working on an interface to call it from CVXPY, work is here https://github.com/cvxpy/cvxpy/pull/2312 , I wonder if you have any comments or suggestions about it. Happy to give you write privileges on that branch if you'd like to make any change. Thanks!

**Comment by darnstrom** [comment]
Thanks a lot @enzbus for starting this interface to CVXPY; it looks great!

Some thoughts:
* Is simple bounds of the form x <= b marked in a special way in  CVXPY? DAQP can handle such constraint in a special way, which can yield significant speedups.
* Similarly, is there some way in CVXPY to mark double-sided inequalities? This is also supported in DAQP and can also result in significant speedups.  
* DAQP supports code generation, so it would be interesting in a second step to integrate it with cvxpygen (I have thought about this before, but have not found the time to look into it.)

**Comment by enzbus** [comment]
Thanks @darnstrom and happy to help! I'm afraid the answer is no to the first two questions, and I don't know to the third.

- CVXPY's compilation model follows the solver interface of solvers like [ECOS](https://github.com/embotech/ecos-python) and [SCS](https://www.cvxgrp.org/scs/api/python.html#python-interface), AFAIK at least, whose constraints are expressed as `A @ x <= b`. [People are looking](https://github.com/cvxpy/cvxpy/pull/2234) into changing the compilation process to support variable bounds natively but it's not there yet. 
- I modeled the DAQP interface after [OSQP's](https://github.com/cvxpy/cvxpy/blob/master/cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py), which also supports double-sided inequality bounds; its CVXPY interface uses the same trick (`-np.inf`). An author of OSQP is also a maintainer of CVXPY but I'm not aware of efforts to compile double-sided inequalities natively.
- I'm not familiar with codegen (I've only tried it), I know it is based on CVXPY, though, so this will probably help.

I wonder if you have any comments on the `eps_prox` part of the interface specifically, or maybe would like to adjust other default parameters for use in CVXPY. Thanks!

**Comment by darnstrom** [comment]
Great, thank you for the clarifications @enzbus.

Setting `eps_prox` to `1e-5` if the objective is semi-definite seems like a good solution to me. DAQP can detect singularity in its setup phase, so one could use that instead of externally performing a Cholesky decomposition to detect singulary (but in the current form of DAQP's Pyhon API, your solution is probably the cleanest.)

The default parameters should be fine.
