### ISSUE TITLE
Use DAQP with inequalities constraints and an equality constraint

### ISSUE THREAD

**Issue by MaximeLee** [darnstrom/daqp#33]
Your example only features a quadratic program with inequality constraints, the problem I want to solve is :
minimize       $0.5 x^T*H*x$
with $\sum_i x_i = 1$ and $\forall i, x_i>0$.

What is the preferred/advised way to implement to solve this problem with your API in Python?

Also the following note in your documentation is not completely clear to me:

> Note: When b_lower and b_upper have more elements than the number of rows in A, the first elements of b_lower and b_upper are interpreted as simple bounds.

This means that the additional first elements of b_lower and b_upper are simple bounds for every coordinate of x (eg every $x_i$)?

# First attempt (the first row of A gives the sum equals to one constraint):
```
import numpy as np

import cvxopt
import daqp
import ctypes
import ctypes.util

    # some symmetric matrix
    H = compute_symmetric_matrix(grads)

    n = grads.shape[1]
    f = np.zeros(n,dtype=ctypes.c_double)
    A = np.eye(n+1,dtype=ctypes.c_double)
    # sum = 1 constraint
    A[0, :] = 1.0

    blower = np.zeros(n,dtype=ctypes.c_double)
    bupper = np.ones(n+1,dtype=ctypes.c_double)

    # most are constraints 0<alpha<1
    sense = np.zeros(n,dtype=ctypes.c_double)
    # sum = 1 constraint
    sense[0] = 5

    (xstar,fval,exitflag,info) = daqp.solve(H,f,A,bupper,blower,sense)
```
# Second attempt
```
    H = compute_symmetric_matrix(grads)

    n = grads.shape[1]
    f = np.zeros(n,dtype=ctypes.c_double)
    # sum = 1 constraint
    A = np.ones((1,n),dtype=ctypes.c_double)
    # x>=0 constraint
    blower = np.zeros(2,dtype=ctypes.c_double)

    # most are constraints 0<alpha<1
    sense = np.zeros(2,dtype=ctypes.c_double)
    # sum = 1 constraint
    sense[1] = 5

    (xstar,fval,exitflag,info) = daqp.solve(H,f,A,bupper,blower,sense)

```

Best regards.

**Comment by darnstrom** [comment]
Thank you for opening this issue @MaximeLee!
I think what you are after is something like:
```python
    H = compute_symmetric_matrix(grads)
    n = grads.shape[1]
    f = np.zeros(n,dtype=ctypes.c_double)
   
    # sum(x) == 1 and  0< x < 1
    A = np.ones((1,n),dtype=ctypes.c_double)
    blower = np.zeros(n+1,dtype=ctypes.c_double)
    bupper = np.ones(n+1,dtype=ctypes.c_double)
    blower[n] = 1 # not necessary since equality only looks at bupper, but added for clarity

    sense = np.zeros(n+1,dtype=ctypes.c_double)
    # sum = 1 constraint
    sense[n] = 5

    (xstar,fval,exitflag,info) = daqp.solve(H,f,A,bupper,blower,sense)
```
Note that bupper, blower, and sense should always have the same dimension.
Let me know if the code gives the desired result (note that I have not tried the code myself)

**Comment by MaximeLee** [comment]
It worked in my case with `n=0`.

**Comment by darnstrom** [comment]
If you put `n` to `0`, you would only impose the `sum(x) == 1` constraint,  _not_ the constraint `0 <= x <= 1`

**Comment by MaximeLee** [comment]
Ty. But given this note:

> Note: When b_lower and b_upper have more elements than the number of rows in A, the first elements of b_lower and b_upper are interpreted as simple bounds.

Should I put my equality constraint first (simple bound) ?

**Comment by darnstrom** [comment]
From the cited sentence, you should put the equality constraint "last" (then that the simple bounds ` 0 <= x <=1` corresponds to the first elements of bupper, blower, and sense.) 

Another thing: the type of sense should be c_int not c_double so the declaration of sense should be:
`sense = np.zeros(n+1,dtype=ctypes.c_int)` 
I have edited the suggested code accordingly.
