### ISSUE TITLE
daqp.cmake should be installed as daqpConfig.cmake

### ISSUE THREAD

**Issue by kkofler** [darnstrom/daqp#51]
Otherwise, `find_package` will not find it. See https://github.com/acados/acados/issues/1124 (where you replied that you will change it, but this has not been implemented yet).

**Comment by kkofler** [comment]
Partial workaround for the application's `CMakeLists.txt` (works only if `daqp_DIR` is set explicitly):
```cmake
  if (daqp_DIR)
    if (EXISTS ${daqp_DIR}/daqp.cmake AND NOT EXISTS ${daqp_DIR}/daqpConfig.cmake)
      file(CREATE_LINK ${daqp_DIR}/daqp.cmake ${daqp_DIR}/daqpConfig.cmake SYMBOLIC)
    endif()
  endif()
  find_package(daqp)
```
but it would be easier for everyone if the file were installed so that `find_package` finds it out of the box.

**Comment by darnstrom** [comment]
Thank you for the reminder! Could you check if #52 fixes this?
