### ISSUE TITLE
daqp.cmake does not set INTERFACE_INCLUDE_DIRECTORIES for the daqp target

### ISSUE THREAD

**Issue by kkofler** [darnstrom/daqp#52]
The exported targets `daqp` and `daqpstat` have no `INTERFACE_INCLUDE_DIRECTORIES` defined. (Modern CMake best practices are to set the include directories automatically in the exported targets, as opposed to defining a variable like `daqp_INCLUDE_DIRECTORIES` that has to be handled manually by the application's `CMakeLists.txt`.) As a result, something like `#include <daqp/api.h>` will only work if DAQP is installed to a standard prefix such as `/usr` where `/usr/include` is found by default. Something like `~/daqp/dist/include` will not be found.

You should add something like:
```cmake
target_include_directories(daqp PUBLIC "$<INSTALL_INTERFACE:$<INSTALL_PREFIX>/${CMAKE_INSTALL_INCLUDEDIR}>")
```
to your `CMakeLists.txt` before the `install(TARGETS daqp EXPORT  ${PROJECT_NAME} …)` command (and likewise for `daqpstat`) so that CMake will automatically generate something like:
```cmake
set_target_properties(daqp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)
```
in the generated `daqp.cmake`.

**Comment by kkofler** [comment]
Can be worked around in the application's `CMakeLists.txt` as follows:
```cmake
  if (daqp_FOUND AND daqp_DIR)
    set_target_properties(daqp PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${daqp_DIR}/../include")
  endif()
```
(That probably works only if `daqp_DIR` is set explicitly on the CMake command line, but on the other hand, you probably have to do that anyway if DAQP is not in a standard prefix.)

**Comment by darnstrom** [comment]
Thank you for reporting this! Could you check if #53 fixes this?
